// locations.js
export const locations = [
  {
    id: 1,
    name: 'An Giang',
    districts: [
      {
        id: 101,
        name: 'Huyện An Phú',
        wards: [
          {id: 1011, name: 'Thị Trấn An Phú'},
          {id: 1012, name: 'Thị Trấn Long Bình'},
          {id: 1013, name: 'Xã Đa Phước'},
          {id: 1014, name: 'Xã An Khánh'},
          {id: 1015, name: 'Xã Khánh Bình'},
          {id: 1016, name: 'Xã Nhơn Hội'},
          {id: 1017, name: 'Xã Phú Hội'},
          {id: 1018, name: 'Xã Phú Hữu'},
          {id: 1019, name: 'Xã Phước Hưng'},
          {id: 10110, name: 'Xã Quốc Thái'},
          {id: 10111, name: 'Xã Vĩnh Hậu'},
          {id: 10112, name: 'Xã Vĩnh Hội Đông'},
          {id: 10113, name: 'Xã Vĩnh Lộc'},
          {id: 10114, name: 'Xã Vĩnh Tường'},
        ],
      },
      {
        id: 102,
        name: 'Huyện Châu Phú',
        wards: [
          {id: 1021, name: 'Thị trấn Cái Dầu'},
          {id: 1022, name: 'Thị trấn Vĩnh Thạnh Trung'},
          {id: 1023, name: 'Xã Bình Chánh'},
          {id: 1024, name: 'Xã Bình Long'},
          {id: 1025, name: 'Xã Bình Phú'},
          {id: 1026, name: 'Xã Bình Thuỷ'},
          {id: 1027, name: 'Xã Đào Hữu Cảnh'},
          {id: 1028, name: 'Xã Khánh Hoà'},
          {id: 1029, name: 'Xã Mỹ Đức'},
          {id: 10210, name: 'Xã Mỹ Phú'},
          {id: 10211, name: 'Xã Ô Long Vỹ'},
          {id: 10212, name: 'Xã Thạnh Mỹ Tây'},
        ],
      },
      {
        id: 103,
        name: 'Huyện Châu Thành',
        wards: [
          {id: 1031, name: 'Thị Trấn An Châu'},
          {id: 1032, name: 'Thị Trấn Vĩnh Bình'},
          {id: 1033, name: 'Xã An Hoà'},
          {id: 1034, name: 'Xã Bình Thạnh'},
          {id: 1035, name: 'Xã Cần Đăng'},
          {id: 1036, name: 'Xã Hoà Bình Thạnh'},
          {id: 1037, name: 'Xã Tân Phú'},
          {id: 1038, name: 'Xã Vĩnh An'},
          {id: 1039, name: 'Xã Vĩnh Hanh'},
          {id: 10310, name: 'Xã Vĩnh Lợi'},
          {id: 10311, name: 'Xã Vĩnh Thuận'},
          {id: 10312, name: 'Xã Vĩnh Thành'},
        ],
      },
      {
        id: 104,
        name: 'Huyện Chợ Mới',
        wards: [
          {id: 1041, name: 'Thị Trấn Chợ Mới'},
          {id: 1042, name: 'Thị Trấn Mỹ Luông'},
          {id: 1043, name: 'Xã An Thạnh Trung'},
          {id: 1044, name: 'Xã Bình Phước Xuân'},
          {id: 1045, name: 'Xã Hoà An'},
          {id: 1046, name: 'Xã Kiến An'},
          {id: 1047, name: 'Xã Kiến Thành'},
          {id: 1048, name: 'Xã Long Điền A'},
          {id: 1049, name: 'Xã Long Điền B'},
          {id: 10410, name: 'Xã Long Giang'},
          {id: 10411, name: 'Xã Long Kiến'},
          {id: 10412, name: 'Xã Mỹ An'},
          {id: 10413, name: 'Xã Mỹ Hiệp'},
          {id: 10414, name: 'Xã Mỹ Hội Đông'},
          {id: 10415, name: 'Xã Nhơn Mỹ'},
          {id: 10416, name: 'Xã Tấn Mỹ'},
        ],
      },
      {
        id: 105,
        name: 'Huyện Phú Tân',
        wards: [
          {id: 1051, name: 'Thị Trấn Chợ Vàm'},
          {id: 1052, name: 'Thị Trấn Phú Mỹ'},
          {id: 1053, name: 'Xã Bình Thạnh Đông'},
          {id: 1054, name: 'Xã Hiệp Xương'},
          {id: 1055, name: 'Xã Hoà Lạc'},
          {id: 1056, name: 'Xã Long Hoà'},
          {id: 1057, name: 'Xã Phú An'},
          {id: 1058, name: 'Xã Phú Bình'},
          {id: 1059, name: 'Xã Phú Hiệp'},
          {id: 10510, name: 'Xã Phú Hưng'},
          {id: 10511, name: 'Xã Phú Lâm'},
          {id: 10512, name: 'Xã Phú Long'},
          {id: 10513, name: 'Xã Phú Thành'},
          {id: 10514, name: 'Xã Phú Thạnh'},
          {id: 10515, name: 'Xã Phú Thọ'},
          {id: 10516, name: 'Xã Phú Xuân'},
          {id: 10517, name: 'Xã Tân Hoà'},
          {id: 10518, name: 'Xã Tân Trung'},
        ],
      },
      {
        id: 106,
        name: 'Huyện Thoại Sơn',
        wards: [
          {id: 1061, name: 'Thị Trấn Núi Sập'},
          {id: 1062, name: 'Thị Trấn Óc Heo'},
          {id: 1063, name: 'Thị Trấn Phú Hoà'},
          {id: 1064, name: 'Xã An Bình'},
          {id: 1065, name: 'Xã Bình Thành'},
          {id: 1066, name: 'Xã Định Mỹ'},
          {id: 1067, name: 'Xã Định Thành'},
          {id: 1068, name: 'Xã Mỹ Phú Đông'},
          {id: 1069, name: 'Xã Phú Thuận'},
          {id: 10610, name: 'Xã Tây Phú'},
          {id: 10611, name: 'Xã Thoại Giang'},
          {id: 10612, name: 'Xã Vĩnh Chánh'},
          {id: 10613, name: 'Xã Vĩnh Khánh'},
          {id: 10614, name: 'Xã Vĩnh Phú'},
          {id: 10615, name: 'Xã Vĩnh Trạch'},
          {id: 10616, name: 'Xã Vọng Đông'},
          {id: 10617, name: 'Xã Vọng Thê'},
        ],
      },
      {
        id: 107,
        name: 'Huyện Tịnh Biên',
        wards: [
          {id: 1071, name: 'Thị Trấn Chi Lăng'},
          {id: 1072, name: 'Thị Trấn Nhà Bàng'},
          {id: 1073, name: 'Thị Trấn Tịnh Biên'},
          {id: 1074, name: 'Xã An Cư'},
          {id: 1075, name: 'Xã An Hảo'},
          {id: 1076, name: 'Xã An Nông'},
          {id: 1077, name: 'Xã An Phú'},
          {id: 1078, name: 'Xã Nhơn Hưng'},
          {id: 1079, name: 'Xã Núi Voi'},
          {id: 10710, name: 'Xã Tân Lập'},
          {id: 10711, name: 'Xã Tân Lợi'},
          {id: 10712, name: 'Xã Thới Sơn'},
          {id: 10713, name: 'Xã Văn Giáo'},
          {id: 10714, name: 'Xã Vĩnh Trung'},
        ],
      },
      {
        id: 108,
        name: 'Huyện Tri Tôn',
        wards: [
          {id: 1081, name: 'Thị Trấn Ba Trúc'},
          {id: 1082, name: 'Thị Trấn Cô Tô'},
          {id: 1083, name: 'Thị Trấn Tri Tôn'},
          {id: 1084, name: 'Xã An Tức'},
          {id: 1085, name: 'Xã Châu Lăng'},
          {id: 1086, name: 'Xã Lạc Quới'},
          {id: 1087, name: 'Xã Lê Trì'},
          {id: 1088, name: 'Xã Lương An Trà'},
          {id: 1089, name: 'Xã Lương Phi'},
          {id: 10810, name: 'Xã Núi Tô'},
          {id: 10811, name: 'Xã Ô Lâm'},
          {id: 10812, name: 'Xã Tà Đảnh'},
          {id: 10813, name: 'Xã Tân Tuyến'},
          {id: 10814, name: 'Xã Vĩnh Gia'},
          {id: 10815, name: 'Xã Vĩnh Phước'},
        ],
      },
      {
        id: 109,
        name: 'Thành Phố Châu Đốc',
        wards: [
          {id: 1091, name: 'Phường Châu Phú A'},
          {id: 1092, name: 'Phường Châu Phú B'},
          {id: 1093, name: 'Phường Núi Sam'},
          {id: 1094, name: 'Phường Vĩnh Mỹ'},
          {id: 1095, name: 'Phường Vĩnh Ngươn'},
          {id: 1096, name: 'Xã Vĩnh Châu'},
          {id: 1097, name: 'Xã Vĩnh Tế'},
        ],
      },
      {
        id: 1010,
        name: 'Thành Phố Long Xuyên',
        wards: [
          {id: 10101, name: 'Phường Bình Đức'},
          {id: 10102, name: 'Phường Bình Khánh'},
          {id: 10103, name: 'Phường Đông Xuyên'},
          {id: 10104, name: 'Phường Mỹ Bình'},
          {id: 10105, name: 'Phường Mỹ Hoà'},
          {id: 10106, name: 'Phường Mỹ Long'},
          {id: 10107, name: 'Phường Mỹ Phước'},
          {id: 10108, name: 'Phường Mỹ Quý'},
          {id: 10109, name: 'Phường Mỹ Thạnh'},
          {id: 101010, name: 'Phường Mỹ Thới'},
          {id: 101011, name: 'Phường Mỹ Xuyên'},
          {id: 101012, name: 'Xã Mỹ Hưng Hoà'},
          {id: 101013, name: 'Xã Mỹ Khánh'},
        ],
      },
      {
        id: 1011,
        name: 'Thị Xã Tân Châu',
        wards: [
          {id: 10111, name: 'Phường Long Châu'},
          {id: 10112, name: 'Phường Long Hưng'},
          {id: 10113, name: 'Phường Long Phú'},
          {id: 10114, name: 'Phường Long Sơn'},
          {id: 10115, name: 'Phường Long Thạnh'},
          {id: 10116, name: 'Xã Châu Phong'},
          {id: 10117, name: 'Xã Lê Chánh'},
          {id: 10118, name: 'Xã Long An'},
          {id: 10119, name: 'Xã Phú Lộc'},
          {id: 101110, name: 'Xã Phú Vĩnh'},
          {id: 101111, name: 'Xã Tân An'},
          {id: 101112, name: 'Xã Tân Thạnh'},
          {id: 101113, name: 'Xã Vĩnh Hoà'},
          {id: 101114, name: 'Xã Vĩnh Xương'},
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Bà Rịa - Vũng Tàu',
    districts: [
      {
        id: 201,
        name: 'Huyện Châu Đức',
        wards: [
          {id: 2011, name: 'Thị Trấn Ngãi Giao'},
          {id: 2012, name: 'Xã Bầu Chinh'},
          {id: 2013, name: 'Xã Bình Ba'},
          {id: 2014, name: 'Xã Bình Giã'},
          {id: 2015, name: 'Xã Bình Trung'},
          {id: 2016, name: 'Xã Cù Bị'},
          {id: 2017, name: 'Xã Đá Bạc'},
          {id: 2018, name: 'Xã Kim Long'},
          {id: 2019, name: 'Xã Láng Lớn'},
          {id: 20110, name: 'Xã Nghĩa Thành'},
          {id: 20111, name: 'Xã Quảng Thành'},
          {id: 20112, name: 'Xã Sơn Bình'},
          {id: 20113, name: 'Xã Suối Nghệ'},
          {id: 20114, name: 'Xã Suối Rao'},
          {id: 20115, name: 'Xã Xà Bang'},
          {id: 20116, name: 'Xã Xuân Sơn'},
        ],
      },
      {
        id: 202,
        name: 'Huyện Côn Đảo',
        wards: [{id: 2021, name: 'Xã Côn Đảo'}],
      },
      {
        id: 203,
        name: 'Huyện Đất Đỏ',
        wards: [
          {id: 2031, name: 'Thị Trấn Đất Đỏ'},
          {id: 2032, name: 'Thị Trấn Phước Hải'},
          {id: 2033, name: 'Xã Láng Đài'},
          {id: 2034, name: 'Xã Long Mỹ'},
          {id: 2035, name: 'Xã Long Tân'},
          {id: 2036, name: 'Xã Lộc An'},
          {id: 2037, name: 'Xã Phước Hội'},
          {id: 2038, name: 'Xã Phước Long Thọ'},
        ],
      },
      {
        id: 204,
        name: 'Huyện Long Điền',
        wards: [
          {id: 2041, name: 'Thị Trấn Long Điền'},
          {id: 2042, name: 'Thị Trấn Long Hải'},
          {id: 2043, name: 'Xã An Ngãi'},
          {id: 2044, name: 'Xã An Nhứt'},
          {id: 2045, name: 'Xã Phước Hưng'},
          {id: 2046, name: 'Xã Phước Tình'},
          {id: 2047, name: 'Xã Tam Phước'},
        ],
      },
      {
        id: 205,
        name: 'Huyện Xuyên Mộc',
        wards: [
          {id: 2051, name: 'Thị Trấn Phước Bửu'},
          {id: 2052, name: 'Xã Bàu Lâm'},
          {id: 2053, name: 'Xã Bình Châu'},
          {id: 2054, name: 'Xã Bông Trang'},
          {id: 2055, name: 'Xã Bưng Riềng'},
          {id: 2056, name: 'Xã Hoà Bình'},
          {id: 2057, name: 'Xã Hoà Hiệp'},
          {id: 2058, name: 'Xã Hoà Hội'},
          {id: 2059, name: 'Xã Hoà Hưng'},
          {id: 20510, name: 'Xã Phước Tân'},
          {id: 20511, name: 'Xã Phước Thuận'},
          {id: 20512, name: 'Xã Tân Lâm'},
          {id: 20513, name: 'Xã Xuyên Mộc'},
        ],
      },
      {
        id: 206,
        name: 'Thành Phố Bà Rịa',
        wards: [
          {id: 2061, name: 'Phường Kim Dinh'},
          {id: 2062, name: 'Phường Long Hương'},
          {id: 2063, name: 'Phường Long Tâm'},
          {id: 2064, name: 'Phường Long Toàn'},
          {id: 2065, name: 'Phường Phước Hiệp'},
          {id: 2066, name: 'Phường Phước Hưng'},
          {id: 2067, name: 'Phường Phước Nguyên'},
          {id: 2068, name: 'Phường Phước Trung'},
          {id: 2069, name: 'Xã Hoà Long'},
          {id: 20610, name: 'Xã Long Phước'},
          {id: 20611, name: 'Xã Tân Hưng'},
        ],
      },
      {
        id: 207,
        name: 'Thành Phố Vũng Tàu',
        wards: [
          {id: 2071, name: 'Phường 1'},
          {id: 2072, name: 'Phường 2'},
          {id: 2073, name: 'Phường 3'},
          {id: 2074, name: 'Phường 4'},
          {id: 2075, name: 'Phường 5'},
          {id: 2076, name: 'Phường 6'},
          {id: 2077, name: 'Phường 7'},
          {id: 2078, name: 'Phường 8'},
          {id: 2079, name: 'Phường 9'},
          {id: 20710, name: 'Phường 10'},
          {id: 20711, name: 'Phường 11'},
          {id: 20712, name: 'Phường 12'},
          {id: 20713, name: 'Phường Nguyễn An Ninh'},
          {id: 20714, name: 'Phường Rạch Dừa'},
          {id: 20715, name: 'Phường Thắng Nhất'},
          {id: 20716, name: 'Phường Thắng Nhì'},
          {id: 20717, name: 'Phường Thắng Tam'},
          {id: 20718, name: 'Xã Long Sơn '},
        ],
      },
      {
        id: 208,
        name: 'Thị Xã Phú Mỹ',
        wards: [
          {id: 2081, name: 'Phường Hắc Dịch'},
          {id: 2082, name: 'Phường Mỹ Xuân'},
          {id: 2083, name: 'Phường Phú Mỹ'},
          {id: 2084, name: 'Phường Phước Hoà'},
          {id: 2085, name: 'Phường Tân Phước'},
          {id: 2086, name: 'Xã Châu Pha'},
          {id: 2087, name: 'Xã Sông Xoài'},
          {id: 2088, name: 'Xã Tân Hải'},
          {id: 2089, name: 'Xã Tân Hoà'},
          {id: 20810, name: 'Xã Tóc Tiên'},
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Bạc Liêu',
    districts: [
      {
        id: 301,
        name: 'Huyện Đông Hải',
        wards: [
          {id: 3011, name: 'Thị Trấn Gành Hào'},
          {id: 3012, name: 'Xã An Phúc'},
          {id: 3013, name: 'Xã An Trạch'},
          {id: 3014, name: 'Xã An Trạch A'},
          {id: 3015, name: 'Xã Điền Hải'},
          {id: 3016, name: 'Xã Định Thành'},
          {id: 3017, name: 'Xã Định Thành A'},
          {id: 3018, name: 'Xã Long Điền'},
          {id: 3019, name: 'Xã Long Điền Đông'},
          {id: 30110, name: 'Xã Long Điền Đông A'},
          {id: 30111, name: 'Xã Long Điền Tây'},
        ],
      },
      {
        id: 302,
        name: 'Huyện Hoà Bình',
        wards: [
          {id: 3021, name: 'Thị Trấn Hoà Bình'},
          {id: 3022, name: 'Xã Minh Diệu'},
          {id: 3023, name: 'Xã Vĩnh Bình'},
          {id: 3024, name: 'Xã Vĩnh Hậu'},
          {id: 3025, name: 'Xã Vĩnh Hậu A'},
          {id: 3026, name: 'Xã Vĩnh Mỹ'},
          {id: 3027, name: 'Xã Vĩnh Mỹ A'},
          {id: 3028, name: 'Xã Vĩnh Mỹ B'},
          {id: 3029, name: 'Xã Vĩnh Thịnh'},
        ],
      },
      {
        id: 303,
        name: 'Huyện Hồng Dân',
        wards: [
          {id: 3031, name: 'Thị Trấn Ngan Dừa'},
          {id: 3032, name: 'Xã Lộc Ninh'},
          {id: 3033, name: 'Xã Ninh Hoà'},
          {id: 3034, name: 'Xã Ninh Quới'},
          {id: 3035, name: 'Xã Ninh Quới A'},
          {id: 3036, name: 'Xã Ninh Thạnh Lợi'},
          {id: 3037, name: 'Xã Ninh Thạnh Lợi A'},
          {id: 3038, name: 'Xã Vĩnh Lộc'},
          {id: 3039, name: 'Xã Vĩnh Lộc A'},
        ],
      },
      {
        id: 304,
        name: 'Huyện Phước Long',
        wards: [
          {id: 3041, name: 'Thị Trấn Phước Long'},
          {id: 3042, name: 'Xã Hưng Phú'},
          {id: 3043, name: 'Xã Phong Thạnh Tây A'},
          {id: 3044, name: 'Xã Phong Thạnh Tây B'},
          {id: 3045, name: 'Xã Phước Long'},
          {id: 3046, name: 'Xã Vĩnh Phú Đông'},
          {id: 3047, name: 'Xã Vĩnh Phú Tây'},
          {id: 3048, name: 'Xã Vĩnh Thanh'},
        ],
      },
      {
        id: 305,
        name: 'Huyện Vĩnnh Lợi',
        wards: [
          {id: 3051, name: 'Thị Trấn Châu Hưng'},
          {id: 3052, name: 'Xã Châu Hưng A'},
          {id: 3053, name: 'Xã Châu Thới'},
          {id: 3054, name: 'Xã Hưng Hội'},
          {id: 3055, name: 'Xã Hưng Thành'},
          {id: 3056, name: 'Xã Long Thạnh'},
          {id: 3057, name: 'Xã Vĩnh Hưng'},
          {id: 3058, name: 'Xã Vĩnh Hưng A'},
        ],
      },
      {
        id: 306,
        name: 'Thành Phố Bạc Liêu',
        wards: [
          {id: 3061, name: 'Phường 1'},
          {id: 3062, name: 'Phường 2'},
          {id: 3063, name: 'Phường 3'},
          {id: 3064, name: 'Phường 5'},
          {id: 3065, name: 'Phường 7'},
          {id: 3066, name: 'Phường 8'},
          {id: 3067, name: 'Phường Nhà Mát'},
          {id: 3068, name: 'Xã Hiệp Thành'},
          {id: 3069, name: 'Xã Vĩnh Trạch'},
          {id: 30610, name: 'Xã Vĩnh Trạch Đông'},
        ],
      },
      {
        id: 307,
        name: 'Thị Xã Giá Rai',
        wards: [
          {id: 3071, name: 'Phường 1'},
          {id: 3072, name: 'Phường Hộ Phòng'},
          {id: 3073, name: 'Phường Láng Tròn'},
          {id: 3074, name: 'Xã Phong Tân'},
          {id: 3075, name: 'Xã Phong Thạnh'},
          {id: 3076, name: 'Xã Phong Thạnh A'},
          {id: 3077, name: 'Xã Phong Thạnh Đông'},
          {id: 3078, name: 'Xã Phong Thạnh Tây'},
          {id: 3079, name: 'Xã Tân Phong'},
          {id: 30710, name: 'Xã Tân Thạnh'},
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Bắc Giang',
    districts: [
      {
        id: 401,
        name: 'Huyện Hiệp Hoà',
        wards: [
          {id: 4011, name: 'Thị Trấn Thắng'},
          {id: 4012, name: 'Xã Bắc Lý'},
          {id: 4013, name: 'Xã Châu Minh'},
          {id: 4014, name: 'Xã Danh Thắng'},
          {id: 4015, name: 'Xã Đại Thành'},
          {id: 4016, name: 'Xã Đoan Bái'},
          {id: 4017, name: 'Xã Đông Lỗ'},
          {id: 4018, name: 'Xã Đồng Tân'},
          {id: 4019, name: 'Xã Hoà Sơn'},
          {id: 40110, name: 'Xã Hoàng An'},
          {id: 40111, name: 'Xã Hoàng Lương'},
          {id: 40112, name: 'Xã Hoàng Thanh'},
          {id: 40113, name: 'Xã Hoàng Vân'},
          {id: 40114, name: 'Xã Hợp Thịnh'},
          {id: 40115, name: 'Xã Hùng Sơn'},
          {id: 40116, name: 'Xã Hương Lâm'},
          {id: 40117, name: 'Xã Lương Phong'},
          {id: 40118, name: 'Xã Mai Đình'},
          {id: 40119, name: 'Xã Mai Trung'},
          {id: 40120, name: 'Xã Ngọc Sơn'},
          {id: 40121, name: 'Xã Quang Minh'},
          {id: 40122, name: 'Xã Thái Sơn'},
          {id: 40123, name: 'Xã Thanh Vân'},
          {id: 40124, name: 'Xã Thường Thắng'},
          {id: 40125, name: 'Xã Xuân Cẩm'},
        ],
      },
      {
        id: 402,
        name: 'Huyện Lạng Giang',
        wards: [
          {id: 4021, name: 'Thị Trấn Kép'},
          {id: 4022, name: 'Thị Trấn Vôi'},
          {id: 4023, name: 'Xã An Hà'},
          {id: 4024, name: 'Xã Dương Đức'},
          {id: 4025, name: 'Xã Đại Lâm'},
          {id: 4026, name: 'Xã Đào Mỹ'},
          {id: 4027, name: 'Xã Hương Lạc'},
          {id: 4028, name: 'Xã Hương Sơn'},
          {id: 4029, name: 'Xã Mỹ Hà'},
          {id: 40210, name: 'Xã Mỹ Thái'},
          {id: 40211, name: 'Xã Nghĩa Hoà'},
          {id: 40212, name: 'Xã Nghĩa Hưng'},
          {id: 40213, name: 'Xã Quang Thịnh'},
          {id: 40214, name: 'Xã Tân Dĩnh'},
          {id: 40215, name: 'Xã Tân Hưng'},
          {id: 40216, name: 'Xã Tân Thanh'},
          {id: 40217, name: 'Xã Thái Đào'},
          {id: 40218, name: 'Xã Tiên Lục'},
          {id: 40219, name: 'Xã Xuân Hương'},
          {id: 40220, name: 'Xã Xương Lâm'},
          {id: 40221, name: 'Xã Yên Mỹ'},
        ],
      },
      {
        id: 403,
        name: 'Huyện Lục Nam',
        wards: [
          {id: 4031, name: 'Thị Trấn Đồi Ngô'},
          {id: 4032, name: 'Xã Bảo Đài'},
          {id: 4033, name: 'Xã Bảo Sơn'},
          {id: 4034, name: 'Xã Bắc Lũng'},
          {id: 4035, name: 'Xã Bình Sơn'},
          {id: 4036, name: 'Xã Cẩm Lý'},
          {id: 4037, name: 'Xã Chu Điện'},
          {id: 4038, name: 'Xã Cương Sơn'},
          {id: 4039, name: 'Xã Đan Hội'},
          {id: 40310, name: 'Xã Đông Hưng'},
          {id: 40311, name: 'Xã Đông Phú'},
          {id: 40312, name: 'Xã Huyền Sơn'},
          {id: 40313, name: 'Xã Khám Lạng'},
          {id: 40314, name: 'Xã Lan Mẫu'},
          {id: 40315, name: 'Xã Lục Sơn'},
          {id: 40316, name: 'Xã Nghĩa Phương'},
          {id: 40317, name: 'Xã Phương Sơn'},
          {id: 40318, name: 'Xã Tam Dị'},
          {id: 40319, name: 'Xã Thanh Lâm'},
          {id: 40320, name: 'Xã Tiên Nha'},
          {id: 40321, name: 'Xã Trường Giang'},
          {id: 40322, name: 'Xã Trường Sơn'},
          {id: 40323, name: 'Xã Vô Tranh'},
          {id: 40324, name: 'Xã Vũ Xá'},
          {id: 40325, name: 'Xã Yên Sơn'},
        ],
      },
      {
        id: 404,
        name: 'Huyện Lục Ngạn',
        wards: [
          {id: 4041, name: 'Thị Trấn Chũ'},
          {id: 4042, name: 'Xã Biển Động'},
          {id: 4043, name: 'Xã Biên Sơn'},
          {id: 4044, name: 'Xã Cấm Sơn'},
          {id: 4045, name: 'Xã Đèo Gia'},
          {id: 4046, name: 'Xã Đồng Cốc'},
          {id: 4047, name: 'Xã Giáp Sơn'},
          {id: 4048, name: 'Xã Hộ Đáp'},
          {id: 4049, name: 'Xã Hồng Giang'},
          {id: 40410, name: 'Xã Kiên Lao'},
          {id: 40411, name: 'Xã Kiên Thành'},
          {id: 40412, name: 'Xã Kim Sơn'},
          {id: 40413, name: 'Xã Mỹ An'},
          {id: 40414, name: 'Xã Nam Dương'},
          {id: 40415, name: 'Xã Phì Điền'},
          {id: 40416, name: 'Xã Phong Minh'},
          {id: 40417, name: 'Xã Phong Vân'},
          {id: 40418, name: 'Xã Phú Nhuận'},
          {id: 40419, name: 'Xã Phượng Sơn'},
          {id: 40420, name: 'Xã Quý Sơn'},
          {id: 40421, name: 'Xã Sơn Hải'},
          {id: 40422, name: 'Xã Tân Hoa'},
          {id: 40423, name: 'Xã Tân Lập'},
          {id: 40424, name: 'Xã Tân Mộc'},
          {id: 40425, name: 'Xã Tân Quang'},
          {id: 40426, name: 'Xã Tân Sơn'},
          {id: 40427, name: 'Xã Thanh Hải'},
          {id: 40428, name: 'Xã Trù Hựu'},
          {id: 40429, name: 'Xã Xa Lý'},
        ],
      },
      {
        id: 405,
        name: 'Huyện Sơn Động',
        wards: [
          {id: 4051, name: 'Thị Trấn An Châu'},
          {id: 4052, name: 'Thị Trấn Tây Yên Tử'},
          {id: 4053, name: 'Xã An Bá'},
          {id: 4054, name: 'Xã An Lạc'},
          {id: 4055, name: 'Xã Cẩm Đàn'},
          {id: 4056, name: 'Xã Dương Hưu'},
          {id: 4057, name: 'Xã Đại Sơn'},
          {id: 4058, name: 'Xã Giáo Liêm'},
          {id: 4059, name: 'Xã Hữu Sản'},
          {id: 40510, name: 'Xã Long Sơn'},
          {id: 40511, name: 'Xã Phúc Sơn'},
          {id: 40512, name: 'Xã Thanh Luận'},
          {id: 40513, name: 'Xã Tuấn Đạo'},
          {id: 40514, name: 'Xã Vân Sơn'},
          {id: 40515, name: 'Xã Vĩnh An'},
          {id: 40516, name: 'Xã Yên Định'},
        ],
      },
      {
        id: 406,
        name: 'Huyện Tân Yên',
        wards: [
          {id: 4061, name: 'Thị Trấn Cao Thượng'},
          {id: 4062, name: 'Thị Trấn Nhã Nam'},
          {id: 4063, name: 'Xã An Dương'},
          {id: 4064, name: 'Xã Cao Xá'},
          {id: 4065, name: 'Xã Đại Hoá'},
          {id: 4066, name: 'Xã Hợp Đức'},
          {id: 4067, name: 'Xã Lam Cốt'},
          {id: 4068, name: 'Xã Lan Giới'},
          {id: 4069, name: 'Xã Liên Chung'},
          {id: 40610, name: 'Xã Liên Sơn'},
          {id: 40611, name: 'Xã Ngọc Châu'},
          {id: 40612, name: 'Xã Ngọc Lý'},
          {id: 40613, name: 'Xã Ngọc Thiện'},
          {id: 40614, name: 'Xã Ngọc Vân'},
          {id: 40615, name: 'Xã Phúc Hoà'},
          {id: 40616, name: 'Xã Phúc Sơn'},
          {id: 40617, name: 'Xã Quang Tiến'},
          {id: 40618, name: 'Xã Quế Nham'},
          {id: 40619, name: 'Xã Song Vân'},
          {id: 40620, name: 'Xã Tân Trung'},
          {id: 40621, name: 'Xã Việt Lập'},
          {id: 40622, name: 'Xã Việt Ngọc'},
        ],
      },
      {
        id: 407,
        name: 'Huyện Việt Yên',
        wards: [
          {id: 4071, name: 'Thị Trấn Bích Động'},
          {id: 4072, name: 'Thị Trấn Nếnh'},
          {id: 4073, name: 'Xã Hồng Thái'},
          {id: 4074, name: 'Xã Hương Mai'},
          {id: 4075, name: 'Xã Minh Đức'},
          {id: 4076, name: 'Xã Nghĩa Trung'},
          {id: 4077, name: 'Xã Ninh Sơn'},
          {id: 4078, name: 'Xã Quang Châu'},
          {id: 4079, name: 'Xã Quảng Minh'},
          {id: 40710, name: 'Xã Tăng Tiến'},
          {id: 40711, name: 'Xã Thượng Lan'},
          {id: 40712, name: 'Xã Tiên Sơn'},
          {id: 40713, name: 'Xã Trung Sơn'},
          {id: 40714, name: 'Xã Tự Lạn'},
          {id: 40715, name: 'Xã Vân Hà'},
          {id: 40716, name: 'Xã Vân Trung'},
          {id: 40717, name: 'Xã Việt Tiến'},
        ],
      },
      {
        id: 408,
        name: 'Huyện Yên Dũng',
        wards: [
          {id: 4081, name: 'Thị Trấn Nham Điền'},
          {id: 4082, name: 'Thị Trấn Tân An'},
          {id: 4083, name: 'Xã Cảnh Thuỵ'},
          {id: 4084, name: 'Xã Đồng Phúc'},
          {id: 4085, name: 'Xã Đồng Việt'},
          {id: 4086, name: 'Xã Đức Giang'},
          {id: 4087, name: 'Xã Hương Gián'},
          {id: 4088, name: 'Xã Lãng Sơn'},
          {id: 4089, name: 'Xã Lão Hộ'},
          {id: 40810, name: 'Xã Nội Hoàng'},
          {id: 40811, name: 'Xã Tân Liễu'},
          {id: 40812, name: 'Xã Tiến Dũng'},
          {id: 40813, name: 'Xã Tiền Phong'},
          {id: 40814, name: 'Xã Trí Yên'},
          {id: 40815, name: 'Xã Tư Mại'},
          {id: 40816, name: 'Xã Xuân Phú'},
          {id: 40817, name: 'Xã Yên Lư'},
        ],
      },
      {
        id: 409,
        name: 'Huyện Yên Thế',
        wards: [
          {id: 4091, name: 'Thị Trấn Bố Hạ'},
          {id: 4092, name: 'Thị Trấn Phồn Xương'},
          {id: 4093, name: 'Xã An Thượng'},
          {id: 4094, name: 'Xã Canh Nậu'},
          {id: 4095, name: 'Xã Đồng Hưu'},
          {id: 4096, name: 'Xã Đồng Kỳ'},
          {id: 4097, name: 'Xã Đồng Lạc'},
          {id: 4098, name: 'Xã Đông Sơn'},
          {id: 4099, name: 'Xã Đồng Tâm'},
          {id: 40910, name: 'Xã Đồng Vương'},
          {id: 40911, name: 'Xã Hồng Kỳ'},
          {id: 40912, name: 'Xã Hương Vĩ'},
          {id: 40913, name: 'Xã Tam Hiệp'},
          {id: 40914, name: 'Xã Tam Tiến'},
          {id: 40915, name: 'Xã Tân Hiệp'},
          {id: 40916, name: 'Xã Tân Sỏi'},
          {id: 40917, name: 'Xã Tiến Thắng'},
          {id: 40918, name: 'Xã Xuân Lương'},
        ],
      },
      {
        id: 4010,
        name: 'Thành Phố Bắc Giang',
        wards: [
          {id: 40101, name: 'Phường Dĩnh Kế'},
          {id: 40102, name: 'Phường Đa Mai'},
          {id: 40103, name: 'Phường Hoàng Văn Thụ'},
          {id: 40104, name: 'Phường Lê Lợi'},
          {id: 40105, name: 'Phường Mỹ Độ'},
          {id: 40106, name: 'Phường Ngô Quyền'},
          {id: 40107, name: 'Phường Thọ Xương'},
          {id: 40108, name: 'Phường Trần Nguyên Hãn'},
          {id: 40109, name: 'Phường Trần Phú'},
          {id: 401010, name: 'Phường Xương Giang'},
          {id: 401011, name: 'Xã Dĩnh Trì'},
          {id: 401012, name: 'Xã Đồng Sơn'},
          {id: 401013, name: 'Xã Song Khê'},
          {id: 401014, name: 'Xã Song Mai'},
          {id: 401015, name: 'Xã Tân Mỹ'},
          {id: 401016, name: 'Xã Tân Tiến'},
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Bắc Kạn',
    districts: [
      {
        id: 501,
        name: 'Huyện Ba Bể',
        wards: [
          {id: 5011, name: 'Thị Trấn Chợ Rã'},
          {id: 5012, name: 'Xã Bành Trạch'},
          {id: 5013, name: 'Xã Cao Thượng'},
          {id: 5014, name: 'Xã Chu Hương'},
          {id: 5015, name: 'Xã Địa Linh'},
          {id: 5016, name: 'Xã Đồng Phúc'},
          {id: 5017, name: 'Xã Hà Hiệu'},
          {id: 5018, name: 'Xã Hoàng Trĩ'},
          {id: 5019, name: 'Xã Khang Ninh'},
          {id: 50110, name: 'Xã Mỹ Phương'},
          {id: 50111, name: 'Xã Nam Mẫu'},
          {id: 50112, name: 'Xã Phúc Lộc'},
          {id: 50113, name: 'Xã Quảng Khê'},
          {id: 50114, name: 'Xã Thuợng Giáo'},
          {id: 50115, name: 'Xã Yến Dương'},
        ],
      },
      {
        id: 502,
        name: 'Huyện Bạch Thông',
        wards: [
          {id: 5021, name: 'Thị Trấn Phủ Thông'},
          {id: 5022, name: 'Xã Cao Sơn'},
          {id: 5023, name: 'Xã Cẩm Giàng'},
          {id: 5024, name: 'Xã Dương Phong'},
          {id: 5025, name: 'Xã Đôn Phong'},
          {id: 5026, name: 'Xã Lục Bình'},
          {id: 5027, name: 'Xã Mỹ Thanh'},
          {id: 5028, name: 'Xã Nguyên Phúc'},
          {id: 5029, name: 'Xã Quang Thuận'},
          {id: 50210, name: 'Xã Quân Hà'},
          {id: 50211, name: 'Xã Sĩ Bình'},
          {id: 50212, name: 'Xã Tân Tú'},
          {id: 50213, name: 'Xã Vi Hương'},
          {id: 50214, name: 'Xã Vũ Muộn'},
        ],
      },
      {
        id: 503,
        name: 'Huyện Chợ Đồn',
        wards: [
          {id: 5031, name: 'Thị Trấn Bằng Lũng'},
          {id: 5032, name: 'Xã Bản Thi'},
          {id: 5033, name: 'Xã Bằng Lãng'},
          {id: 5034, name: 'Xã Bằng Phúc'},
          {id: 5035, name: 'Xã Bình Trung'},
          {id: 5036, name: 'Xã Đại Sảo'},
          {id: 5037, name: 'Xã Đồng Lạc'},
          {id: 5038, name: 'Xã Đồng Thắng'},
          {id: 5039, name: 'Xã Lương Bằng'},
          {id: 50310, name: 'Xã Nam Cường'},
          {id: 50311, name: 'Xã Nghĩa Tá'},
          {id: 50312, name: 'Xã Ngọc Phái'},
          {id: 50313, name: 'Xã Phương Viên'},
          {id: 50314, name: 'Xã Quảng Bạch'},
          {id: 50315, name: 'Xã Tân Lập'},
          {id: 50316, name: 'Xã Xuân Lạc'},
          {id: 50317, name: 'Xã Yên Mỹ'},
          {id: 50318, name: 'Xã Yên Phong'},
          {id: 50319, name: 'Xã Yên Thịnh'},
          {id: 50320, name: 'Xã Yên Thượng'},
        ],
      },
      {
        id: 504,
        name: 'Huyện Chợ Mới',
        wards: [
          {id: 5041, name: 'Thị Trấn Đồng Tâm'},
          {id: 5042, name: 'Xã Bình Văn'},
          {id: 5043, name: 'Xã Cao Kỳ'},
          {id: 5044, name: 'Xã Hoà Mục'},
          {id: 5045, name: 'Xã Mai Lạp'},
          {id: 5046, name: 'Xã Như Cố'},
          {id: 5047, name: 'Xã Nông Hạ'},
          {id: 5048, name: 'Xã Quảng Chu'},
          {id: 5049, name: 'Xã Tân Sơn'},
          {id: 50410, name: 'Xã Thanh Mai'},
          {id: 50411, name: 'Xã Thanh Thịnh'},
          {id: 50412, name: 'Xã Thanh Vận'},
          {id: 50413, name: 'Xã Yên Cư'},
          {id: 50414, name: 'Xã Yên Hân'},
        ],
      },
      {
        id: 505,
        name: 'Huyện Na Rì',
        wards: [
          {id: 5051, name: 'Thị Trấn Yến Lạc'},
          {id: 5052, name: 'Xã Côn Minh'},
          {id: 5053, name: 'Xã Cư Lễ'},
          {id: 5054, name: 'Xã Cường Lợi'},
          {id: 5055, name: 'Xã Dương Sơn'},
          {id: 5056, name: 'Xã Đổng Xá'},
          {id: 5057, name: 'Xã Kim Hỷ'},
          {id: 5058, name: 'Xã Kim Lư'},
          {id: 5059, name: 'Xã Liêm Thuỷ'},
          {id: 50510, name: 'Xã Lương Thượng'},
          {id: 50511, name: 'Xã Quang Phong'},
          {id: 50512, name: 'Xã Sơn Thành'},
          {id: 50513, name: 'Xã Trần Phú'},
          {id: 50514, name: 'Xã Văn Lang'},
          {id: 50515, name: 'Xã Văn Minh'},
          {id: 50516, name: 'Xã Văn Vũ'},
          {id: 50517, name: 'Xã Xuân Dương'},
        ],
      },
      {
        id: 506,
        name: 'Huyện Ngân Sơn',
        wards: [
          {id: 5061, name: 'Thị Trấn Nà Phặc'},
          {id: 5062, name: 'Xã Bằng Vân'},
          {id: 5063, name: 'Xã Cốc Đán'},
          {id: 5064, name: 'Xã Đức Vân'},
          {id: 5065, name: 'Xã Hiệp Lực'},
          {id: 5066, name: 'Xã Thuần Mang'},
          {id: 5067, name: 'Xã Thuợng Ân'},
          {id: 5068, name: 'Xã Thuợng Quan'},
          {id: 5069, name: 'Xã Trung Hoà'},
          {id: 50610, name: 'Xã Vân Tùng'},
        ],
      },
      {
        id: 507,
        name: 'Huyện Pắc Nặm',
        wards: [
          {id: 5071, name: 'Xã An Thắng'},
          {id: 5072, name: 'Xã Bằng Thành'},
          {id: 5073, name: 'Xã Bộc Bố'},
          {id: 5074, name: 'Xã Cao Tân'},
          {id: 5075, name: 'Xã Cổ Linh'},
          {id: 5076, name: 'Xã Công Bằng'},
          {id: 5077, name: 'Xã Giáo Hiệu'},
          {id: 5078, name: 'Xã Nghiên Loan'},
          {id: 5079, name: 'Xã Nhạn Môn'},
          {id: 50710, name: 'Xã Xuân La'},
        ],
      },
      {
        id: 508,
        name: 'Thành Phố Bắc Kạn',
        wards: [
          {id: 5081, name: 'Phường Đức Xuân'},
          {id: 5082, name: 'Phường Huyền Tụng'},
          {id: 5083, name: 'Phường Nguyễn Thị Minh Khai'},
          {id: 5084, name: 'Phường Phùng Chí Kiên'},
          {id: 5085, name: 'Phường Sông Cầu'},
          {id: 5086, name: 'Phường Xuất Hoá'},
          {id: 5087, name: 'Xã Dương Quang'},
          {id: 5088, name: 'Xã Nông Thượng'},
        ],
      },
    ],
  },
  {
    id: 6,
    name: 'Bắc Ninh',
    districts: [
      {
        id: 601,
        name: 'Huyện Gia Bình',
        wards: [
          {id: 6011, name: 'Thị Trán Gia Bình'},
          {id: 6012, name: 'Xã Bình Dương'},
          {id: 6013, name: 'Xã Cao Đức'},
          {id: 6014, name: 'Xã Đại Bái'},
          {id: 6015, name: 'Xã Đại Lai'},
          {id: 6016, name: 'Xã Đông Cứu'},
          {id: 6017, name: 'Xã Giang Sơn'},
          {id: 6018, name: 'Xã Lãng Ngâm'},
          {id: 6019, name: 'Xã Nhân Thắng'},
          {id: 60110, name: 'Xã Quỳnh Phú'},
          {id: 60111, name: 'Xã Song Giang'},
          {id: 60112, name: 'Xã Thái Bảo'},
          {id: 60113, name: 'Xã Vạn Ninh'},
          {id: 60114, name: 'Xã Xuân Lai'},
        ],
      },
      {
        id: 602,
        name: 'Huyện Lương Tài',
        wards: [
          {id: 6021, name: 'Thị Trấn Thứa'},
          {id: 6022, name: 'Xã An Thịnh'},
          {id: 6023, name: 'Xã Bình Định'},
          {id: 6024, name: 'Xã Lai Hạ'},
          {id: 6025, name: 'Xã Lâm Thao'},
          {id: 6026, name: 'Xã Minh Tân'},
          {id: 6027, name: 'Xã Mỹ Hương'},
          {id: 6028, name: 'Xã Phú Hoà'},
          {id: 6029, name: 'Xã Phú Lương'},
          {id: 60210, name: 'Xã Quảng Phú'},
          {id: 60211, name: 'Xã Tân Lãng'},
          {id: 60212, name: 'Xã Trung Chính'},
          {id: 60213, name: 'Xã Trung Kênh'},
          {id: 60214, name: 'Xã Trừng Xá'},
        ],
      },
      {
        id: 602,
        name: 'Huyện Quế Võ',
        wards: [
          {id: 6031, name: 'Thị Trấn Phố Mới'},
          {id: 6032, name: 'Xã Bằng An'},
          {id: 6033, name: 'Xã Bồng Lai'},
          {id: 6034, name: 'Xã Cách Bi'},
          {id: 6035, name: 'Xã Châu Phong'},
          {id: 6036, name: 'Xã Chi Lăng'},
          {id: 6037, name: 'Xã Đại Xuân'},
          {id: 6038, name: 'Xã Đào Viên'},
          {id: 6039, name: 'Xã Đức Long'},
          {id: 60310, name: 'Xã Hán Quảng'},
          {id: 60311, name: 'Xã Mộ Đạo'},
          {id: 60312, name: 'Xã Ngọc Xá'},
          {id: 60313, name: 'Xã Nhân Hoà'},
          {id: 60314, name: 'Xã Phù Lãng'},
          {id: 60315, name: 'Xã Phù Lương'},
          {id: 60316, name: 'Xã Phương Liễu'},
          {id: 60317, name: 'Xã Phượng Mao'},
          {id: 60318, name: 'Xã Quế Tân'},
          {id: 60319, name: 'Xã Việt Hùng'},
          {id: 60320, name: 'Xã Việt Thống'},
          {id: 60321, name: 'Xã Yên Giả'},
        ],
      },
      {
        id: 604,
        name: 'Huyện Thuận Thành',
        wards: [
          {id: 6041, name: 'Thị Trấn Hồ'},
          {id: 6042, name: 'Xã An Bình'},
          {id: 6043, name: 'Xã Đại Đồng Thành'},
          {id: 6044, name: 'Xã Đình Tổ'},
          {id: 6045, name: 'Xã Gia Đông'},
          {id: 6046, name: 'Xã Hà Mãn'},
          {id: 6047, name: 'Xã Hoài Thượng'},
          {id: 6048, name: 'Xã Mão Điền'},
          {id: 6049, name: 'Xã Nghĩa Đạo'},
          {id: 60410, name: 'Xã Ngũ Thái'},
          {id: 60411, name: 'Xã Nguyệt Đức'},
          {id: 60412, name: 'Xã Ninh Xá'},
          {id: 60413, name: 'Xã Song Hồ'},
          {id: 60414, name: 'Xã Song Liễu'},
          {id: 60415, name: 'Xã Thanh Khương'},
          {id: 60416, name: 'Xã Trạm Lộ'},
          {id: 60417, name: 'Xã Trí Quả'},
          {id: 60418, name: 'Xã Xuân Lâm'},
        ],
      },
      {
        id: 605,
        name: 'Huyện Tiên Du',
        wards: [
          {id: 6051, name: 'Thị Trấn Lim'},
          {id: 6052, name: 'Xã Cảnh Hưng'},
          {id: 6053, name: 'Xã Đại Đồng'},
          {id: 6054, name: 'Xã Hiên Vân'},
          {id: 6055, name: 'Xã Hoàn Sơn'},
          {id: 6056, name: 'Xã Lạc Vệ'},
          {id: 6057, name: 'Xã Liên Bão'},
          {id: 6058, name: 'Xã Minh Đạo'},
          {id: 6059, name: 'Xã Nội Duệ'},
          {id: 60510, name: 'Xã Phật Tích'},
          {id: 60511, name: 'Xã Phú Lâm'},
          {id: 60512, name: 'Xã Tân Chi'},
          {id: 60513, name: 'Xã Tri Phương'},
          {id: 60514, name: 'Xã Việt Đoàn'},
        ],
      },
      {
        id: 606,
        name: 'Huyện Yên Phong',
        wards: [
          {id: 6061, name: 'Thị Trấn Chờ'},
          {id: 6062, name: 'Xã Dũng Liệt'},
          {id: 6063, name: 'Xã Đông Phong'},
          {id: 6064, name: 'Xã Đông Thọ'},
          {id: 6065, name: 'Xã Đông Tiến'},
          {id: 6066, name: 'Xã Hoà Tiến'},
          {id: 6067, name: 'Xã Long Châu'},
          {id: 6068, name: 'Xã Tam Đa'},
          {id: 6069, name: 'Xã Tam Giang'},
          {id: 60610, name: 'Xã Thuỵ Hoà'},
          {id: 60611, name: 'Xã Trung Nghĩa'},
          {id: 60612, name: 'Xã Văn Môn'},
          {id: 60613, name: 'Xã Yên Phụ'},
          {id: 60614, name: 'Xã Yên Trung'},
        ],
      },
      {
        id: 607,
        name: 'Thành phố Bắc Ninh',
        wards: [
          {id: 6071, name: 'Phường Đại Phúc'},
          {id: 6072, name: 'Phường Đáp Cầu'},
          {id: 6073, name: 'Phường Hạp Lĩnh'},
          {id: 6074, name: 'Phường Hoà Long'},
          {id: 6075, name: 'Phường Khắc Niệm'},
          {id: 6076, name: 'Phường Khúc Xuyên'},
          {id: 6077, name: 'Phường Kim Chân'},
          {id: 6078, name: 'Phường Kinh Bắc'},
          {id: 6079, name: 'Phường Nam Sơn'},
          {id: 60710, name: 'Phường Ninh Xá'},
          {id: 60711, name: 'Phường Phong Khê'},
          {id: 60712, name: 'Phường Suối Hoa'},
          {id: 60713, name: 'Phường Thị Cầu'},
          {id: 60714, name: 'Phường Tiền An'},
          {id: 60715, name: 'Phường Vạn An'},
          {id: 60716, name: 'Phường Vân Dương'},
          {id: 60717, name: 'Phường Vệ An'},
          {id: 60718, name: 'Phường Võ Cường'},
          {id: 60719, name: 'Phường Vũ Ninh'},
        ],
      },
      {
        id: 608,
        name: 'Thành phố Từ Sơn',
        wards: [
          {id: 6081, name: 'Phường Châu Khê'},
          {id: 6082, name: 'Phường Đình Bảng'},
          {id: 6083, name: 'Phường Đồng Kỵ'},
          {id: 6084, name: 'Phường Đông Ngàn'},
          {id: 6085, name: 'Phường Đồng Nguyên'},
          {id: 6086, name: 'Phường Hương Mạc'},
          {id: 6087, name: 'Phường Phù Chuẩn'},
          {id: 6088, name: 'Phường Phù Khê'},
          {id: 6089, name: 'Phường Tam Sơn'},
          {id: 60810, name: 'Phường Tân Hồng'},
          {id: 60811, name: 'Phường Trang Hạ'},
          {id: 60812, name: 'Phường Tương Giang'},
        ],
      },
    ],
  },
  {
    id: 7,
    name: 'Bến Tre',
    districts: [
      {
        id: 701,
        name: 'Thành phố Bến Tre',
        wards: [{id: 7011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 8,
    name: 'Bình Định',
    districts: [
      {
        id: 801,
        name: 'Thành phố Quy Nhơn',
        wards: [{id: 8011, name: 'Phường Quyết Thắng'}],
      },
    ],
  },
  {
    id: 9,
    name: 'Bình Dương',
    districts: [
      {
        id: 901,
        name: 'Thành phố Thủ Dầu Một',
        wards: [{id: 9011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 10,
    name: 'Bình Phước',
    districts: [
      {
        id: 1001,
        name: 'Thành phố Đồng Xoài',
        wards: [{id: 10011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 11,
    name: 'Bình Thuận',
    districts: [
      {
        id: 1101,
        name: 'Thành phố Phan Thiết',
        wards: [{id: 11011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 12,
    name: 'Cà Mau',
    districts: [
      {
        id: 1201,
        name: 'Thành phố Cà Mau',
        wards: [{id: 12011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 13,
    name: 'Cần Thơ',
    districts: [
      {
        id: 1301,
        name: 'Thành phố Cần Thơ',
        wards: [{id: 13011, name: 'Phường Xuân Khánh'}],
      },
    ],
  },
  {
    id: 14,
    name: 'Cao Bằng',
    districts: [
      {
        id: 1401,
        name: 'Thành phố Cao Bằng',
        wards: [{id: 14011, name: 'Phường Quang Hưng'}],
      },
    ],
  },
  {
    id: 15,
    name: 'Đà Nẵng',
    districts: [
      {
        id: 1501,
        name: 'Quận Hải Châu',
        wards: [{id: 15011, name: 'Phường Hòa Thuận Đông'}],
      },
    ],
  },
  {
    id: 16,
    name: 'Đắk Lắk',
    districts: [
      {
        id: 1601,
        name: 'Thành phố Buôn Ma Thuột',
        wards: [{id: 16011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 17,
    name: 'Đắk Nông',
    districts: [
      {
        id: 1701,
        name: 'Thành phố Gia Nghĩa',
        wards: [{id: 17011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 18,
    name: 'Điện Biên',
    districts: [
      {
        id: 1801,
        name: 'Thành phố Điện Biên Phủ',
        wards: [{id: 18011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 19,
    name: 'Đồng Nai',
    districts: [
      {
        id: 1901,
        name: 'Thành phố Biên Hòa',
        wards: [{id: 19011, name: 'Phường Tân Hiệp'}],
      },
    ],
  },
  {
    id: 20,
    name: 'Đồng Tháp',
    districts: [
      {
        id: 2001,
        name: 'Thành phố Cao Lãnh',
        wards: [{id: 20011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 21,
    name: 'Gia Lai',
    districts: [
      {
        id: 2101,
        name: 'Thành phố Pleiku',
        wards: [{id: 21011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 22,
    name: 'Hà Giang',
    districts: [
      {
        id: 2201,
        name: 'Thành phố Hà Giang',
        wards: [{id: 22011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 23,
    name: 'Hà Nam',
    districts: [
      {
        id: 2301,
        name: 'Thành phố Phủ Lý',
        wards: [{id: 23011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 24,
    name: 'Hà Nội',
    districts: [
      {
        id: 2401,
        name: 'Quận Ba Đình',
        wards: [{id: 24011, name: 'Phường Phúc Xá'}],
      },
    ],
  },
  {
    id: 25,
    name: 'Hà Tĩnh',
    districts: [
      {
        id: 2501,
        name: 'Thành phố Hà Tĩnh',
        wards: [{id: 25011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 26,
    name: 'Hải Dương',
    districts: [
      {
        id: 2601,
        name: 'Thành phố Hải Dương',
        wards: [{id: 26011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 27,
    name: 'Hải Phòng',
    districts: [
      {
        id: 2701,
        name: 'Quận Hồng Bàng',
        wards: [{id: 27011, name: 'Phường Hồng Bàng'}],
      },
    ],
  },
  {
    id: 28,
    name: 'Hậu Giang',
    districts: [
      {
        id: 2801,
        name: 'Thành phố Vị Thanh',
        wards: [{id: 28011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 29,
    name: 'Hòa Bình',
    districts: [
      {
        id: 2901,
        name: 'Thành phố Hòa Bình',
        wards: [{id: 29011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 30,
    name: 'Hưng Yên',
    districts: [
      {
        id: 3001,
        name: 'Thành phố Hưng Yên',
        wards: [{id: 30011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 31,
    name: 'Khánh Hòa',
    districts: [
      {
        id: 3101,
        name: 'Thành phố Nha Trang',
        wards: [{id: 31011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 32,
    name: 'Kiên Giang',
    districts: [
      {
        id: 3201,
        name: 'Thành phố Rạch Giá',
        wards: [{id: 32011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 33,
    name: 'Kon Tum',
    districts: [
      {
        id: 3301,
        name: 'Thành phố Kon Tum',
        wards: [{id: 33011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 34,
    name: 'Lai Châu',
    districts: [
      {
        id: 3401,
        name: 'Thành phố Lai Châu',
        wards: [{id: 34011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 35,
    name: 'Lâm Đồng',
    districts: [
      {
        id: 3501,
        name: 'Thành phố Đà Lạt',
        wards: [{id: 35011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 36,
    name: 'Lạng Sơn',
    districts: [
      {
        id: 3601,
        name: 'Thành phố Lạng Sơn',
        wards: [{id: 36011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 37,
    name: 'Lào Cai',
    districts: [
      {
        id: 3701,
        name: 'Thành phố Lào Cai',
        wards: [{id: 37011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 38,
    name: 'Long An',
    districts: [
      {
        id: 3801,
        name: 'Thành phố Tân An',
        wards: [{id: 38011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 39,
    name: 'Nam Định',
    districts: [
      {
        id: 3901,
        name: 'Thành phố Nam Định',
        wards: [{id: 39011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 40,
    name: 'Nghệ An',
    districts: [
      {
        id: 4001,
        name: 'Thành phố Vinh',
        wards: [{id: 40011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 41,
    name: 'Ninh Bình',
    districts: [
      {
        id: 4101,
        name: 'Thành phố Ninh Bình',
        wards: [{id: 41011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 42,
    name: 'Ninh Thuận',
    districts: [
      {
        id: 4201,
        name: 'Thành phố Phan Rang',
        wards: [{id: 42011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 43,
    name: 'Phú Thọ',
    districts: [
      {
        id: 4301,
        name: 'Thành phố Việt Trì',
        wards: [{id: 43011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 44,
    name: 'Phú Yên',
    districts: [
      {
        id: 4401,
        name: 'Thành phố Tuy Hòa',
        wards: [{id: 44011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 45,
    name: 'Quảng Bình',
    districts: [
      {
        id: 4501,
        name: 'Thành phố Đồng Hới',
        wards: [{id: 45011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 46,
    name: 'Quảng Nam',
    districts: [
      {
        id: 4601,
        name: 'Thành phố Hội An',
        wards: [{id: 46011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 47,
    name: 'Quảng Ngãi',
    districts: [
      {
        id: 4701,
        name: 'Thành phố Quảng Ngãi',
        wards: [{id: 47011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 48,
    name: 'Quảng Ninh',
    districts: [
      {
        id: 4801,
        name: 'Thành phố Hạ Long',
        wards: [{id: 48011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 49,
    name: 'Quảng Trị',
    districts: [
      {
        id: 4901,
        name: 'Thành phố Đông Hà',
        wards: [{id: 49011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 50,
    name: 'Sóc Trăng',
    districts: [
      {
        id: 5001,
        name: 'Thành phố Sóc Trăng',
        wards: [{id: 50011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 51,
    name: 'Sơn La',
    districts: [
      {
        id: 5101,
        name: 'Thành phố Sơn La',
        wards: [{id: 51011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 52,
    name: 'Tây Ninh',
    districts: [
      {
        id: 5201,
        name: 'Thành phố Tây Ninh',
        wards: [{id: 52011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 53,
    name: 'Thái Bình',
    districts: [
      {
        id: 5301,
        name: 'Thành phố Thái Bình',
        wards: [{id: 53011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 54,
    name: 'Thái Nguyên',
    districts: [
      {
        id: 5401,
        name: 'Thành phố Thái Nguyên',
        wards: [{id: 54011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 55,
    name: 'Thanh Hóa',
    districts: [
      {
        id: 5501,
        name: 'Thành phố Thanh Hóa',
        wards: [{id: 55011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 56,
    name: 'Thừa Thiên Huế',
    districts: [
      {
        id: 5601,
        name: 'Thành phố Huế',
        wards: [{id: 56011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 57,
    name: 'Tiền Giang',
    districts: [
      {
        id: 5701,
        name: 'Thành phố Mỹ Tho',
        wards: [{id: 57011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 58,
    name: 'TP Hồ Chí Minh',
    districts: [
      {
        id: 5801,
        name: 'Quận 1',
        wards: [{id: 58011, name: 'Phường Tân Định'}],
      },
    ],
  },
  {
    id: 59,
    name: 'Trà Vinh',
    districts: [
      {
        id: 5901,
        name: 'Thành phố Trà Vinh',
        wards: [{id: 59011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 60,
    name: 'Tuyên Quang',
    districts: [
      {
        id: 6001,
        name: 'Thành phố Tuyên Quang',
        wards: [{id: 60011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 61,
    name: 'Vĩnh Long',
    districts: [
      {
        id: 6101,
        name: 'Thành phố Vĩnh Long',
        wards: [{id: 61011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 62,
    name: 'Vĩnh Phúc',
    districts: [
      {
        id: 6201,
        name: 'Thành phố Vĩnh Yên',
        wards: [{id: 62011, name: 'Phường 1'}],
      },
    ],
  },
  {
    id: 63,
    name: 'Yên Bái',
    districts: [
      {
        id: 6301,
        name: 'Thành phố Yên Bái',
        wards: [{id: 63011, name: 'Phường 1'}],
      },
    ],
  },
];
